In [1]:
import numpy as np
import pandas as pd

In [2]:
#Files to stack together
#Read the mouse data and the study results

February_2020 = pd.read_csv("JC_202002_citibike_tripdata.csv")
March_2020 = pd.read_csv("JC_202003_citibike_tripdata.csv")
April_2020 = pd.read_csv("JC_202004_citibike_tripdata.csv")
May_2020 = pd.read_csv("JC_202005_citibike_tripdata.csv")
June_2020 = pd.read_csv('JC_202006_citibike_tripdata.csv')
July_2020 = pd.read_csv('JC_202007_citibike_tripdata.csv')
August_2020 = pd.read_csv('JC_202008_citibike_tripdata.csv')
September_2020 = pd.read_csv('JC_202009_citibike_tripdata.csv')

In [29]:
June_2020['start station name'].unique()

array(['Columbus Dr at Exchange Pl', 'Heights Elevator', 'Columbus Drive',
       'Morris Canal', 'Harborside', 'Grove St PATH', 'York St',
       'Sip Ave', 'Hilltop', 'Oakland Ave', 'Lincoln Park',
       'Glenwood Ave', 'Hamilton Park', 'Newport Pkwy',
       'Baldwin at Montgomery', 'Washington St', 'Newark Ave',
       'Bergen Ave', 'Essex Light Rail', 'Christ Hospital',
       'Liberty Light Rail', 'Brunswick St', 'Marin Light Rail',
       'Monmouth and 6th', 'JC Medical Center', 'Van Vorst Park',
       'Jersey & 6th St', 'McGinley Square', 'Paulus Hook', 'Astor Place',
       'Hoboken Ave at Monmouth St', 'City Hall', 'Dey St',
       'Riverview Park', 'Jersey & 3rd', 'Pershing Field',
       'Journal Square', 'Union St', 'Manila & 1st', 'Newport PATH',
       'Warren St', 'Dixon Mills', 'Montgomery St', 'Jackson Square',
       '5 Corners Library', 'Grand St', 'Lafayette Park',
       'Communipaw & Berry Lane', 'Fairmount Ave', 'Brunswick & 6th',
       'Leonard Gordon Park'], dtype=object)

In [3]:
import glob

df = pd.concat(map(pd.read_csv, glob.glob('*.csv')))

In [4]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1

In [34]:
March_2020.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1

In [23]:
df.shape

(247727, 18)

In [5]:
df['gender'] = df['gender'].astype(str)

In [6]:
df['Gender'] = df['gender'].replace(['0','1','2'],['Unknown','Male','Female'])

In [7]:
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1,Male
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1,Male
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0,Unknown
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1,Male
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,0,Unknown
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,1,Male
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,1,Male
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,1,Male
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,1,Male

In [8]:
del df['gender']

In [9]:
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,Gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,Male
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,Male
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,Unknown
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,Male
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,Unknown
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,Male
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,Male
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,Male
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,Male

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 247727 entries, 0 to 9267
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tripduration             247727 non-null  int64
 1   starttime                247727 non-null  object
 2   stoptime                 247727 non-null  object
 3   start station id         247727 non-null  int64
 4   start station name       247727 non-null  object
 5   start station latitude   247727 non-null  float64
 6   start station longitude  247727 non-null  float64
 7   end station id           247727 non-null  int64
 8   end station name         247727 non-null  object
 9   end station latitude     247727 non-null  float64
 10  end station longitude    247727 non-null  float64
 11  bikeid                   247727 non-null  int64
 12  usertype                 247727 non-null  object
 13  birth year               247727 non-null  int64
 14  Gender                   247727 non-null  object
dtypes: float64(4), int64(5), object(6)
memory usage: 30.2+ MB

In [11]:
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,Gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,Male
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,Male
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,Unknown
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,Male
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,Unknown
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,Male
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,Male
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,Male
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,Male

In [12]:
df['Trip Year']= df.starttime.str.split('-', expand=True)[0]

In [13]:
df['Trip Month']= df.starttime.str.split('-', expand=True)[1]

In [14]:
df['Trip Year']=df['Trip Year'].astype('int')

In [15]:
#age of riders
df['Age'] = df['Trip Year']- df['birth year']

In [16]:
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,Gender,Trip Year,Trip Month,Age
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,Male,2020,03,28
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,Male,2020,03,29
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,Unknown,2020,03,33
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,Male,2020,03,27
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,Male,2020,03,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,Unknown,2020,04,51
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,Male,2020,04,34
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,Male,2020,04,29
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,Male,2020,04,44
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,Male,2020,04,21

In [27]:
df['start station name'].unique()

array(['Newport PATH', 'City Hall', 'Jersey & 3rd', 'McGinley Square',
       'Baldwin at Montgomery', 'Essex Light Rail', 'Manila & 1st',
       'Columbus Drive', 'Fairmount Ave', 'Brunswick St', 'Morris Canal',
       'Marin Light Rail', 'Columbus Dr at Exchange Pl', 'Newark Ave',
       'Hamilton Park', 'Brunswick & 6th', 'Astor Place',
       'JC Medical Center', 'Harborside', 'Sip Ave', 'Washington St',
       'Riverview Park', 'Monmouth and 6th', 'Glenwood Ave',
       'Van Vorst Park', 'Grand St', 'Newport Pkwy', 'Warren St',
       '5 Corners Library', 'Liberty Light Rail', 'Grove St PATH',
       'Montgomery St', 'Oakland Ave', 'Dixon Mills', 'Hilltop',
       'Lafayette Park', 'Christ Hospital', 'Pershing Field',
       'Jackson Square', 'Lincoln Park', 'Dey St',
       'Hoboken Ave at Monmouth St', 'Paulus Hook', 'Journal Square',
       'Communipaw & Berry Lane', 'Jersey & 6th St', 'Heights Elevator',
       'Union St', 'Bergen Ave', 'Leonard Gordon Park', 'York St',
       'JCBS Depot'], dtype=object)

In [32]:
df['bikeid'].count()

247727

In [31]:
df['end station name'].unique()

array(['Hamilton Park', 'JC Medical Center', 'Monmouth and 6th',
       'Washington St', 'Astor Place', 'Jackson Square', 'City Hall',
       'Brunswick & 6th', 'Manila & 1st', 'Harborside',
       'Marin Light Rail', 'Grove St PATH', 'Columbus Dr at Exchange Pl',
       'Newark Ave', 'Warren St', 'Sip Ave', 'Glenwood Ave',
       'Montgomery St', 'Hoboken Ave at Monmouth St', '5 Corners Library',
       'Brunswick St', 'Jersey & 3rd', 'Liberty Light Rail',
       'Van Vorst Park', 'Columbus Drive', 'Journal Square',
       'Pershing Field', 'Newport PATH', 'Hilltop', 'Essex Light Rail',
       'Grand St', 'Communipaw & Berry Lane', 'Dixon Mills',
       'Newport Pkwy', 'Riverview Park', 'Jersey & 6th St', 'Oakland Ave',
       'Lafayette Park', 'Paulus Hook', 'Lincoln Park',
       'Baldwin at Montgomery', 'York St', 'Bergen Ave', 'Morris Canal',
       'McGinley Square', 'Union St', 'Fairmount Ave', 'Dey St',
       'Pier 40 - Hudson River Park', 'Leonard Gordon Park',
       'Christ Hospital', 'Heights Elevator', 'W 129 St & Convent Ave',
       'JCBS Depot', 'Broadway & W 49 St', 'West Thames St',
       'W 45 St & 8 Ave', 'Cabrini Blvd & W 177 St',
       'South St & Gouverneur Ln', 'W 13 St & 7 Ave',
       'Mott St & Prince St', 'Front St & Jay St',
       'Riverside Dr & W 78 St', 'Mercer St & Spring St',
       '12 Ave & W 40 St', 'Little West St & 1 Pl',
       'Riverside Dr & W 138 St', '6 Ave & W 33 St',
       'Harrison St & Hudson St', 'Christopher St & Greenwich St',
       'E 85 St & York Ave', 'West St & Liberty St', 'Wall St & South St',
       'Driggs Ave & N 9 St', 'W 40 St & 5 Ave', 'NYCBS DEPOT - DELANCEY',
       'Hicks St & Montague St', 'W 169 St & Fort Washington Ave',
       'Lenox Ave & W 111 St', 'Front St & Maiden Ln', '1 Ave & E 5 St',
       'W 47 St & 10 Ave', 'Liberty State Park', 'Broadway & W 51 St',
       'Central Park S & 6 Ave', 'Broadway & W 122 St',
       'Vesey Pl & River Terrace', 'West St & Chambers St',
       'Lexington Ave & E 29 St', 'W 34 St & 11 Ave',
       'Willoughby Ave & Hall St', 'Broadway & Moylan Pl',
       'W 120 St & Claremont Ave', 'E 31 St & 3 Ave', 'W 53 St & 10 Ave',
       'Broadway & E 14 St', 'Atlantic Ave & Fort Greene Pl',
       'St James Pl & Pearl St', 'W 21 St & 6 Ave',
       'Fort Washington Ave & W 173 St', 'Watts St & Greenwich St',
       'Greenwich St & W Houston St', 'W 4 St & 7 Ave S',
       'St Nicholas Ave & E 134 St', 'Pier 40 X2',
       'DeKalb Ave & Hudson Ave', 'W 95 St & Broadway',
       'Lenox Ave & W 144 St', '1 Ave & E 16 St',
       'Edgecombe Ave & W 141 St', 'E 123 St & Lexington Ave',
       'Park Pl & Franklin Ave', 'W 52 St & 6 Ave',
       'St James Pl & Oliver St', 'Adam Clayton Powell Blvd & W 126 St',
       'Murray St & Greenwich St', '10 Ave & W 28 St',
       'Water - Whitehall Plaza', 'Clinton St & Joralemon St',
       'E 39 St & 2 Ave', 'North Moore St & Greenwich St',
       'Morningside Ave & W 123 St'], dtype=object)

In [18]:
df.to_csv('df_modified_modified.csv', index=False)